# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_banco_de_horas
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    env_file: 
      - .database_env # Enviroment variables in this file
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - minha_rede
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      retries: 5
      start_period: 10s

networks:
  minha_rede:
    driver: bridge